### ISSUE TITLE
ladda adds two <span class="ladda-spinner"> elements for progress bar demo

### ISSUE THREAD

**Issue by jeacott** [msurguy/ladda-bootstrap#14]
just reporting a possible issue.
if you take a look at the demo for the progress bar buttons,
 you'll see the button element looks like this:

```
<button class="btn btn-danger ladda-button" data-style="expand-right">
<span class="ladda-label">expand-right</span>
<span class="ladda-spinner"></span>
<span class="ladda-spinner"></span>
</button>
```

if I manually remove one of the ladda-spinner elements it still seems to work fine.
is the extra element intended?

**Comment by arielmoraes** [comment]
I faced this problem because I needed to change the state of a instance that was already been create so I came up with this approach, not clean though:

To create the Ladda objects use this:
$(".ladda-button").ladda().ladda("bind");

And to access a specific object use:
$(object).data("ladda").stop();

I found this solution looking at the ladda.jquery file.
