### ISSUE TITLE
Deprecate project in favor of original Ladda

### ISSUE THREAD

**Issue by terales** [msurguy/ladda-bootstrap#68]
Just tested how current version of the original [Ladda](https://github.com/hakimel/Ladda) works with Bootstrap and found that it works really well:

https://jsfiddle.net/terales/p3efcqw7/

@msurguy what do you think about adding deprecation messages, close issues and navigating people to the original Ladda?

**Comment by terales** [comment]
Or maybe this project would be a connector to fix some Bootstrap related edge cases like #65?

**Comment by msurguy** [comment]
@terales yeah, there is no reason to maintain this repo if all problems have been solved by original Ladda plugin. 

What you can do is to create a couple PRs with clear examples of using Bootstrap 3 and Bootstrap 4 with Ladda so that people have an easy reference about how to use Ladda with Bootstrap. By doing that you can essentially clear the confusion that my repo was trying to solve and you can provide solutions to specific edge cases like #65 as well.

Does that sound good?

**Comment by terales** [comment]
Yeah!

Here is a PR for adding Bootstrap 3 and 4 to the test cases inside Ladda: https://github.com/hakimel/Ladda/pull/76

Do you think about adding examples into the repository home page? I think I could help

**Comment by msurguy** [comment]
@terales I think you'd have to consult with @hakimel about that in Ladda repo and ask him whether he thinks it's a good idea.

Thanks for your PRs!

**Comment by terales** [comment]
Closed with https://github.com/msurguy/ladda-bootstrap/commit/25615d82c7639ac88826ef3bc9fdff4dc56cc8a3
